[Options]
AutoFix = true

[Log]
# LogLevel
#
#  0 = trace
#  1 = debug
#  2 = info (default)
#  3 = warning
#  4 = error
#  5 = critical
LogLevel = 2

# LogFlush
#
#  true = flush log file every line (very slow!)
#  false = flush log file only when error level message is logged (default)
LogFlush = false
